version: "3.8"

services:
  app:
    build:
      context: ./src
    container_name: neuralnet-api
    ports:
      - "5000:5000"
    env_file:
      - src/.env
    volumes:
      - ./src:/app
    restart: unless-stopped
