version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: genai-handson-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
    driver: local
