version: 1
formatters:
  default:
    format: "[%(asctime)s] %(levelname)s in %(name)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [ console ]
